version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/back/"
    schedule:
      interval: "weekly"
    assignees:
      - "pylipp"
  - package-ecosystem: "npm"
    directory: "/docs/graphql-api"
    schedule:
      interval: "weekly"
    assignees:
      - "pylipp"
  - package-ecosystem: "npm"
    directory: "/react/"
    schedule:
      interval: "weekly"
