# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        types: [python]
        language: system
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        types: [python]
        language: system
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        types_or: [cython, pyi, python]
        language: system
        require_serial: true
        args: ['--filter-files']
      - id: eslint
        name: eslint
        entry: ./invoke_yarn lint
        files: react/.*\.[jt]sx?$
        types: [file]
        language: script
        require_serial: true
      - id: prettier
        name: prettier
        entry: ./invoke_yarn format
        files: react/.*\.[jt]sx?$
        types: [file]
        language: script
        require_serial: true
      - id: generate-graphql-ts-types
        name: Generate GraphQL Typescript definitions
        entry: ./invoke_yarn graphql-types
        files: back/.*\.graphql$
        types: [file]
        language: script
        require_serial: true
