# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.1.1
  hooks:
  - id: seed-isort-config
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.15.0
  hooks:
  - id: eslint
    # additional_dependencies:
    # - eslint@7.15.0
    # - eslint-config-airbnb@latest
    # - eslint-config-prettier@latest
    # - eslint-config-react-app@latest
    # - eslint-plugin-prettier@latest
    # - eslint-plugin-jsx-a11y@latest
    # - eslint-plugin-import@latest
    # - eslint-plugin-react@latest
    # - eslint-plugin-flowtype@latest
    # - eslint-plugin-react-hooks@latest
    # - babel-eslint@latest
    # - typescript
    # - "@typescript-eslint/parser"
    files: \.[jt]sx?$
    types: [file]
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.2.1 # local node version must be higher than 10
  hooks:
  - id: prettier
    types_or: [javascript, jsx, json, ts, tsx, css, scss]
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    types: [python]
    language: python
    require_serial: true
  - id: flake8
    name: flake8
    entry: flake8
    types: [python]
    language: python
    require_serial: true
