version: '3.2'
services:
    web:
        build: .
        ports:
          - "5000:5000"
        networks:
          - backend
        volumes:
          - .:/codedir
        environment:
          FLASK_ENV: development
    mysql:
        image: mysql/mysql-server:latest
        command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
        environment:
          MYSQL_ROOT_PASSWORD: dropapp_root
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: dropapp_dev
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - "32000:3306"
        networks:
          - backend

networks:
    backend:
        driver: bridge
