version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/project
    steps:
      - checkout
      - run: python3 -m venv env
      - run: source env/bin/activate
      - run: pip install -r requirements.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - attach_workspace:
          at: workspace
      - gcp-cli/install
      - run: |
          cd workspace
workflows:
  build-and-deploy:
    jobs:
    - build
    - deploy
