version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
jobs:
  build-flask:
    docker:
      - image: circleci/python:3.8-buster
    working_directory: ~/flask
    steps:
      - checkout
      # Restore cached dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: create the python virtual environment and install non-cached dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install . -r requirements.txt
      # Cache the installed packages
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - env
      # save build to a CircleCI workspace
      - persist_to_workspace:
          root: ~/flask
          paths:
            - .

  # following https://circleci.com/docs/2.0/project-walkthrough/
  test-flask:
    docker:
      - image: circleci/python:3.8-buster
    working_directory: ~/flask
    steps:
      # Attach workspace from build
      - attach_workspace:
          at: .
      - run:
          name: install dev dependencies for linting and testing
          command: |
            source env/bin/activate
            pip install -r requirements-dev.txt
      # run linting checks
      # run tests https://circleci.com/docs/2.0/collect-test-data/#pytest
      - run:
          name: Run pytest
          command: |
            sourve env/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  deploy:
    parameters:
      serviceName:
        type: string
    docker:
      - image: circleci/python:3.8-buster
    working_directory: ~/flask
    steps:
      # Attach workspace from build
      - attach_workspace:
          at: .
      # install gcloud orb
      - gcp-cli/install
      - run:
          name: Create version.txt
          command: |
            echo "CircleCI build number:${CIRCLE_BUILD_NUM}
              Branch: ${CIRCLE_BRANCH}
              Git hash: ${CIRCLE_SHA1}" > version.txt
      - run:
          name: Generate .env file
          command: |
            echo "
            AUTH0_DOMAIN=${AUTH0_DOMAIN}
            AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
            MYSQL_USER=${DB_NAME}
            MYSQL_PASSWORD=${DB_PASS}
            MYSQL_DB=${DB_NAME}
            GCLOUD_SQL_CONNECTION_NAME=${GCLOUD_SQL_CONNECTION_NAME}" > .env
      - run:
          name: Generate GAE app.yaml file
          command: |
            sed 's/service: api-staging/service: << parameters.serviceName >>/g' app.yaml > app-<< parameters.serviceName >>.yaml
      - run:
          name: Authenticate the gcloud orb
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Deploy to GAE
          command: |
            gcloud app deploy app-<< parameters.serviceName >>.yaml
workflows:
  build-and-deploy:
    jobs:
    - build-flask
    - test-flask:
        requires:
          - build-flask
    # deploy to staging
    - deploy:
        name: deploy-staging
        context: STAGING
        serviceName: api-staging
        requires:
          - test-flask
        filters:
          branches:
            only: feature/add-circleci
    # deploy to demo
    - deploy:
        name: deploy-demo
        context: DEMO
        serviceName: api-demo
        filters:
          branches:
            only: production
    # deploy to production
    - deploy:
        name: deploy-production
        context: PRODUCTION
        serviceName: api-production
        filters:
          branches:
            only: production
