runtime: python310
service: v2-staging
entrypoint: gunicorn -b :$PORT boxtribute_server.main:app
handlers:
  - url: /graphql
    script: auto
    secure: always
  - url: /
    secure: always
    static_files: front-build/index.html
    upload: front-build/index.html
  - url: /manifest.json
    static_files: front-build/manifest.json
    upload: front-build/manifest.json
  - url: /heapanalytics.js
    static_files: front-build/heapanalytics.js
    upload: front-build/heapanalytics.js
  - url: /static/(.*)
    secure: always
    static_files: front-build/static/\1
    upload: front-build/static/(.*)
  - url: /(.*\.(ico|png|svg))$
    secure: always
    static_files: front-build/\1
    upload: front-build/(.*\.(ico|png|svg))$
  - url: /(.*)
    secure: always
    static_files: front-build/index.html
    upload: front-build/index.html
