runtime: python38
service: v2-staging
entrypoint: gunicorn -b :$PORT boxwise_flask.main:app
handlers:
- url: /api/.*
  script: auto
  secure: always
- url: /
  secure: always
  static_dir: react-build/
